"""
🖼️ EasyLLM Image Capture — Save generated images to DB for popup display.

Saves IMAGE tensors from VAE Decode (or any IMAGE output) to the EasyLLM
on-disk database as PNG files. Emits a ``ui_payload`` with ``session_uuid``
and ``node_id`` so the frontend can reconcile generated images with the
correct LLM conversation turn.

Leaf OUTPUT_NODE — no downstream connections needed.

Images are saved with embedded PNG metadata:
  • ``prompt``  — full ComfyUI prompt JSON (for CivitAI compatibility)
  • ``workflow`` — full workflow graph JSON (for drag-and-drop restore)
  • ``easyllm_session`` — custom {session_uuid, timestamp, source}
"""

import json
import logging
import time
import torch

from PIL.PngImagePlugin import PngInfo

from .utils import tensor_to_base64_png

logger = logging.getLogger(__name__)


class EasyLLM_ImageCapture:
    """
    🖼️ EasyLLM Image Capture — Save generated images to DB for popup display.

    Converts IMAGE tensors to PNG, saves to the EasyLLM DB, and emits a
    ``ui_payload`` with ``session_uuid`` + ``node_id`` for frontend
    reconciliation. Handles batched tensors (saves each frame separately).

    Connect:
      VAE Decode IMAGE → this node's ``images`` input
      Trigger Router ``session_uuid``  → this node's ``session_uuid`` input

    Set ``node_id`` widget to the EasyLLM node's canvas ID (e.g., ``123``).
    """

    OUTPUT_NODE = True

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "images": ("IMAGE", {
                    "tooltip": "Image tensor from VAE Decode or any IMAGE output socket",
                }),
            },
            "optional": {
                "session_uuid": ("STRING", {
                    "forceInput": True,
                    "tooltip": (
                        "Session UUID from Trigger Router's session_uuid output. "
                        "Used by frontend to associate this image with the correct "
                        "LLM node's history."
                    ),
                }),
                "capture_mode": (["all", "generate", "edit", "chat"], {
                    "default": "all",
                    "tooltip": (
                        "Which LLM action triggers this capture. "
                        "'all' = always capture (default, backward-compatible). "
                        "'generate' = only when action is generate_image. "
                        "'edit' = only when action is edit_image. "
                        "'chat' = only when action is just_chat."
                    ),
                }),
                "positive_prompt": ("STRING", {
                    "forceInput": True,
                    "tooltip": (
                        "The actual positive prompt text generated by the LLM "
                        "(connect Trigger Router's 'prompt' output here). "
                        "Embedded as CivitAI-readable metadata so the positive "
                        "prompt is recognized even when dynamically generated."
                    ),
                }),
            },
            "hidden": {
                "unique_id": "UNIQUE_ID",
                "prompt": "PROMPT",
                "extra_pnginfo": "EXTRA_PNGINFO",
            },
        }

    RETURN_TYPES = ("BOOLEAN",)
    RETURN_NAMES = ("success",)
    OUTPUT_TOOLTIPS = ("True if image was saved successfully.",)
    FUNCTION = "capture"
    CATEGORY = "EasyLLM/🎛️ Advanced"
    DESCRIPTION = (
        "Saves a generated image to the EasyLLM database and emits a ui_payload "
        "so the frontend can display it in the LLM node's chat popup or enhancer "
        "history. Uses session_uuid to associate the image with the correct LLM "
        "conversation turn.\n\n"
        "Connect: VAE Decode IMAGE → this node's images input.\n"
        "Connect: Trigger Router session_uuid → this node's session_uuid input.\n"
        "Set node_id widget to the LLM node's canvas ID (e.g., '123')."
    )

    def capture(
        self,
        images: torch.Tensor,
        session_uuid: str = "",
        capture_mode: str = "all",
        unique_id: str = "",
        positive_prompt: str = "",
        prompt: dict | None = None,       # injected by ComfyUI execution framework
        extra_pnginfo: dict | None = None,  # injected by ComfyUI execution framework
    ):
        """
        Convert IMAGE tensor to base64, save to DB, emit ui_payload.

        Handles batched tensors (saves all frames).
        unique_id is this node's own ComfyUI node ID (auto-populated via hidden).

        ``prompt`` and ``extra_pnginfo`` are injected automatically by ComfyUI's
        execution framework for any OUTPUT_NODE function that accepts them.
        They are used to embed standard ComfyUI metadata (``prompt`` + ``workflow``)
        and custom EasyLLM session metadata in the saved PNG file.
        """
        # ── Build PNG metadata from ComfyUI context ────────────────
        pnginfo = self._build_pnginfo(
            prompt=prompt,
            extra_pnginfo=extra_pnginfo,
            session_uuid=session_uuid,
            positive_prompt=positive_prompt,
        )

        b64_images = []
        filenames = []

        # ── Python-side capture mode filtering (defense-in-depth) ──
        # The primary routing happens on the frontend (findCaptureNodeForAction
        # targets the correct Capture node via app.queuePrompt(0,1,[nodeId])).
        # This Python-side check handles edge cases like manual canvas queues
        # where the Capture node might execute unexpectedly. We check before
        # processing images to avoid wasted tensor conversion.
        if capture_mode == "chat":
            # Chat-mode captures are text-only; if images arrive here the
            # node was probably wired to an image chain in error.
            logger.debug(
                f"[EasyLLM_ImageCapture] capture_mode=chat — skipping image(s)"
            )
            return {
                "ui": {
                    "session_uuid": [session_uuid],
                    "node_id": [unique_id],
                    "_easyllm_images": [],
                },
                "result": (False,),
            }

        # Handle batched IMAGE tensors (batch of frames)
        if images.dim() == 4 and images.shape[0] > 1:
            for i in range(images.shape[0]):
                single_img = images[i:i + 1]
                b64 = tensor_to_base64_png(single_img, max_size=None, pnginfo=pnginfo)
                fn = self._save_image(b64)
                b64_images.append(b64)
                filenames.append(fn)
        else:
            b64 = tensor_to_base64_png(images, max_size=None, pnginfo=pnginfo)
            fn = self._save_image(b64)
            b64_images.append(b64)
            filenames.append(fn)

        # ── Iterative Refinement: update pipeline cache with generated image ──
        # When iterative_refinement is enabled (per-node widget or config
        # default), overwrite the LLM node's _last_pipeline_image_cache with
        # the generated image tensor so the next edit_image turn uses this
        # result as source instead of the original uploaded image.
        from .config import ITERATIVE_REFINEMENT as _DEFAULT_ITERATIVE_REFINEMENT
        if session_uuid:
            try:
                from .chat_node import (
                    _last_pipeline_image_cache,
                    _session_to_node,
                    _iterative_refinement_flags,
                )
                llm_node_id = _session_to_node.get(session_uuid)
                if llm_node_id is not None:
                    enabled = _iterative_refinement_flags.get(
                        llm_node_id, _DEFAULT_ITERATIVE_REFINEMENT
                    )
                    if enabled:
                        _last_pipeline_image_cache[llm_node_id] = images
                        logger.info(
                            f"[EasyLLM_ImageCapture] Iterative refinement: "
                            f"updated pipeline cache for LLM node {llm_node_id} "
                            f"(shape={images.shape})"
                        )
            except Exception:
                logger.debug(
                    "[EasyLLM_ImageCapture] Iterative refinement cache update "
                    "skipped (non-critical)"
                )

        # Build ui_payload for frontend reconciliation
        # node_id is resolved on frontend via autoDetectLLMNodeId() graph traversal
        ui_payload = {
            "session_uuid": [session_uuid],
            "_easyllm_images": [
                {"type": "generated", "filename": fn}
                for fn in filenames if fn
            ],
        }

        return {
            "ui": ui_payload,
            "result": (len(filenames) > 0,),
        }

    def _build_pnginfo(
        self,
        prompt: dict | None,
        extra_pnginfo: dict | None,
        session_uuid: str,
        positive_prompt: str = "",
    ) -> PngInfo | None:
        """Build PNG metadata from ComfyUI prompt data and session info.

        Embeds up to four independent text chunks in the PNG file:

        1. **``prompt``** — Full ComfyUI prompt JSON (widget values, node
           connections). This is what CivitAI and other tools read to extract
           generation parameters. If ``positive_prompt`` is provided, it is
           injected as a synthetic ``CLIPTextEncode`` node so CivitAI can
           detect the positive prompt even when it's dynamically generated.

        2. **``workflow``** (from ``extra_pnginfo``) — Full workflow graph JSON
           (nodes, positions, links). Enables drag-and-drop workflow restore
           when the image is loaded back into ComfyUI.

        3. **``easyllm_session``** — Custom metadata with ``session_uuid``,
           ``timestamp``, and ``source`` for internal audit trail.

        4. **``easyllm_prompt``** — The clean positive prompt text (if provided
           via the ``positive_prompt`` input). Makes it easy to see the actual
           prompt text used for generation.

        Returns ``None`` if there is nothing to embed.
        """
        if prompt is None and extra_pnginfo is None and not session_uuid and not positive_prompt:
            return None

        metadata = PngInfo()

        # 1. Standard ComfyUI prompt metadata (CivitAI compatibility)
        if prompt is not None:
            try:
                # If a clean positive prompt is available, inject it as a
                # synthetic CLIPTextEncode node so CivitAI can detect it.
                # This solves the "dynamic prompt not recognized" issue.
                if positive_prompt:
                    prompt = self._inject_positive_prompt_to_dict(
                        prompt, positive_prompt
                    )
                metadata.add_text("prompt", json.dumps(prompt))
            except Exception:
                logger.debug(
                    "[EasyLLM_ImageCapture] Failed to serialize prompt metadata"
                )

        # 2. Standard ComfyUI workflow metadata (drag-and-drop restore)
        if extra_pnginfo is not None:
            for k, v in extra_pnginfo.items():
                try:
                    text_value = (
                        json.dumps(v) if isinstance(v, (dict, list)) else str(v)
                    )
                    metadata.add_text(k, text_value)
                except Exception:
                    logger.debug(
                        f"[EasyLLM_ImageCapture] Failed to serialize "
                        f"extra_pnginfo key '{k}'"
                    )

        # 3. Custom EasyLLM session metadata (internal audit trail)
        if session_uuid:
            try:
                session_meta = json.dumps({
                    "session_uuid": session_uuid,
                    "timestamp": time.strftime(
                        "%Y-%m-%dT%H:%M:%S", time.gmtime()
                    ),
                    "source": "EasyLLM_ImageCapture",
                })
                metadata.add_text("easyllm_session", session_meta)
            except Exception:
                logger.debug(
                    "[EasyLLM_ImageCapture] Failed to serialize session metadata"
                )

        # 4. Clean positive prompt text (visible even without CivitAI parsing)
        if positive_prompt:
            try:
                metadata.add_text("easyllm_prompt", positive_prompt)
            except Exception:
                logger.debug(
                    "[EasyLLM_ImageCapture] Failed to serialize positive prompt"
                )

        return metadata

    SYNT_NODE_ID = "999998"  # high numeric ID unlikely to conflict

    def _inject_positive_prompt_to_dict(
        self,
        prompt_dict: dict,
        positive_prompt_text: str,
    ) -> dict:
        """Inject the clean positive prompt into the prompt dict as a
        synthetic CLIPTextEncode node so CivitAI can detect it.

        CivitAI walks the prompt JSON looking for CLIPTextEncode nodes
        with literal text strings. When the positive prompt is dynamically
        generated by an LLM and passed via a link (e.g. ``["53", 0]``),
        CivitAI cannot resolve it.

        This method does two things:
        1. Adds a synthetic ``CLIPTextEncode`` node with key ``999998``
           containing the resolved positive prompt as literal text.
        2. **Rewires** every ``KSampler`` node's ``positive`` input from
           the original link-based CLIPTextEncode to the synthetic node.
           This is critical because CivitAI traces graph connections:
           KSampler → ``positive`` input → CLIPTextEncode → ``text``.
           Without rewiring, CivitAI would follow the original link and
           find unresolvable ``["53", 0]``.

        The ``workflow`` text chunk (used for drag-and-drop restore) is
        **never modified**, so dragging the image back into ComfyUI
        restores the original graph correctly.

        NOTE: We inject REGARDLESS of whether other CLIPTextEncode nodes
        have literal text, because a negative-prompt node with literal text
        (the common ComfyUI workflow pattern) would otherwise suppress
        injection of the positive prompt.
        """
        # Bail out quickly if there's no prompt dict or text
        if not isinstance(prompt_dict, dict) or not positive_prompt_text:
            return prompt_dict

        prompt_dict = dict(prompt_dict)  # shallow copy
        synt_id = self.SYNT_NODE_ID

        # ── Step 1: Find the source CLIPTextEncode node ID ───────────
        # Look for a KSampler whose ``positive`` input is a link to a
        # CLIPTextEncode node whose ``text`` is also a link (dynamic).
        # We'll rewire that source.
        rewired_sources: set[str] = set()
        for node_id, node_data in list(prompt_dict.items()):
            if not isinstance(node_data, dict):
                continue
            ct = node_data.get("class_type", "")
            if "KSampler" not in ct:
                continue  # not a KSampler variant
            pos_input = node_data.get("inputs", {}).get("positive")
            if not isinstance(pos_input, list) or len(pos_input) != 2:
                continue  # not a link
            src_id, src_socket = str(pos_input[0]), int(pos_input[1])
            # Check if the source node is a CLIPTextEncode with link text
            src_data = prompt_dict.get(src_id)
            if not isinstance(src_data, dict):
                continue
            if src_data.get("class_type") != "CLIPTextEncode":
                continue
            src_text = src_data.get("inputs", {}).get("text")
            if isinstance(src_text, str) and src_text:
                continue  # literal text — CivitAI already sees it
            # Source is a link-based CLIPTextEncode — rewire KSampler
            node_data["inputs"]["positive"] = [synt_id, 0]
            rewired_sources.add(src_id)

        if not rewired_sources:
            # No KSampler found with a link-based positive prompt.
            # Fall back to just adding the synthetic node.
            prompt_dict[synt_id] = {
                "inputs": {
                    "text": positive_prompt_text,
                    "clip": ["999999", 0],
                },
                "class_type": "CLIPTextEncode",
                "_meta": {
                    "title": "CLIP Text Encode (Positive) — EasyLLM injected",
                },
            }
            return prompt_dict

        # ── Step 2: Add the synthetic CLIPTextEncode node ────────────
        prompt_dict[synt_id] = {
            "inputs": {
                "text": positive_prompt_text,
                "clip": ["999999", 0],
            },
            "class_type": "CLIPTextEncode",
            "_meta": {
                "title": "CLIP Text Encode (Positive) — EasyLLM injected",
            },
        }

        return prompt_dict

    def _save_image(self, b64: str) -> str | None:
        """Save a single base64 image to DB, returning filename."""
        try:
            from .history_db import save_image_from_base64, is_available, save_image_force
            from .utils import base64_to_bytes
            if is_available():
                return save_image_from_base64(b64, "generated")
            else:
                return save_image_force(base64_to_bytes(b64), "generated")
        except Exception as e:
            import logging
            logging.warning(f"[LLM Chat Image Capture] Failed to save image: {e}")
            return None


# ── Node Registration ──────────────────────────────────────────────────────

NODE_CLASS_MAPPINGS = {"EasyLLM_ImageCapture": EasyLLM_ImageCapture}
NODE_DISPLAY_NAME_MAPPINGS = {"EasyLLM_ImageCapture": "🖼️ EasyLLM Image Capture"}
